import "types.cats"

# V2 entity header with crypto-agile (variable-length) signatures and public keys.
#
# Wire format:
#   [4 bytes]  Size (uint32) — total entity size
#   [1 byte]   CryptoSchemeId — determines signature/key sizes
#   [3 bytes]  Reserved padding
#   [S bytes]  Signature — size S determined by CryptoSchemeId
#   [K bytes]  SignerPublicKey — size K determined by CryptoSchemeId
#   [4 bytes]  Reserved padding
#   [1 byte]   Version
#   [1 byte]   Network (NetworkType)
#   [2 bytes]  Type
#
# For CryptoSchemeId = ED25519 (0x00):
#   S = 64, K = 32 → binary-compatible with V1
#
# For CryptoSchemeId = ML_DSA_65 (0x01):
#   S = 3309, K = 1952
#
# Header_Size (skippable for signing) = 8 + S + K + 4

# Serialization of a V2 entity that has its size stated as a prefix.
inline struct SizePrefixedEntityV2
	# Entity size in bytes.
	size = uint32

# Serialization of a V2 entity that should be signed by an account.
#
# The CryptoSchemeId field replaces the former reserved padding field.
# When CryptoSchemeId = 0x00 (ED25519), the remaining 3 bytes of padding
# are zero, making this binary-compatible with V1 VerifiableEntity.
inline struct VerifiableEntityV2
	# Cryptographic scheme used for signature and public key.
	crypto_scheme_id = CryptoSchemeId

	# Reserved padding to align Signature to an 8-byte boundary.
	verifiable_entity_v2_reserved_1 = make_reserved(uint8, 0)
	verifiable_entity_v2_reserved_2 = make_reserved(uint8, 0)
	verifiable_entity_v2_reserved_3 = make_reserved(uint8, 0)

	# Entity's signature generated by the signing account.
	# Size is determined by crypto_scheme_id:
	#   ED25519: 64 bytes (binary_fixed(64))
	#   ML_DSA_65: 3309 bytes (binary_fixed(3309))
	#
	# NOTE: In catbuffer, this is expressed as scheme-specific concrete types.
	# The abstract V2 layout uses runtime-determined sizes.

# Serialization of a V2 entity body.
inline struct EntityBodyV2
	# Reserved padding to align end of EntityBody to an 8-byte boundary.
	entity_body_v2_reserved_1 = make_reserved(uint32, 0)

	# Version of this structure.
	version = uint8

	# Network on which this entity was created.
	network = NetworkType
